version: '3'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"
    volumes:
      - ".:/src"
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 8000