version: '3'

services:

  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - TZ=Asia/Tokyo
    expose:
      - "5432"

  flask:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"
    volumes:
      - ".:/src"
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 8000
    depends_on: 
      - db

volumes:
  database:
    driver: local